Fix stravalib version to 1.2.0
More recent versions remove abstract types this codebase relies on
currently.

See https://github.com/stravalib/stravalib/blob/main/changelog.md for
the notes on 1.3 where IdentifiableEntity got removed.

```
Traceback (most recent call last):
  File "/usr/local/bin/freezing-sync", line 5, in <module>
    from freezing.sync.run import main
  File "/usr/local/lib/python3.10/dist-packages/freezing/sync/run.py", line 18, in <module>
    from freezing.sync.subscribe import ActivityUpdateSubscriber
  File "/usr/local/lib/python3.10/dist-packages/freezing/sync/subscribe.py", line 12, in <module>
    from freezing.sync.data.activity import ActivitySync
  File "/usr/local/lib/python3.10/dist-packages/freezing/sync/data/activity.py", line 12, in <module>
    from freezing.sync.utils.cache import CachingActivityFetcher
  File "/usr/local/lib/python3.10/dist-packages/freezing/sync/utils/cache.py", line 7, in <module>
    from stravalib.model import Activity, IdentifiableEntity, Stream
ImportError: cannot import name 'IdentifiableEntity' from 'stravalib.model' (/usr/local/lib/python3.10/dist-packages/stravalib/model.py)
```